name: Scheduled Setup asdf tools cache

on:
  schedule:
    - cron: 0 6,12 * * * # Runs every day at 7/8 danish time and 13/14 danish time
  workflow_dispatch: # Allow manual triggering

permissions:
  id-token: write
  contents: read

# The intention is that other workflows can reuse the cached tools installed here.
# It runs twice a day in case the case gets invalidated
jobs:
  setup-tools:
    runs-on: ubuntu-24.04
    steps:
      - name: Install tools
        uses: Energinet-DataHub/.github/.github/actions/asdf-install-tools@actions/v1
